import { useCallback, useEffect, useState } from 'react'
import './App.css'

const API = import.meta.env.VITE_API_URL || 'http://127.0.0.1:5000'
const readToken = () => localStorage.getItem('parkzen-token')
async function api(path, options = {}) {
  const headers = { ...(options.body instanceof FormData ? {} : { 'Content-Type': 'application/json' }), ...(options.headers || {}) }
  if (readToken()) headers.Authorization = `Bearer ${readToken()}`
  const response = await fetch(`${API}${path}`, { ...options, headers })
  const data = await response.json().catch(() => ({}))
  if (!response.ok) throw new Error(data.error || 'Something went wrong. Please try again.')
  return data
}
const mapsUrl = (d) => `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${d.latitude},${d.longitude} (${d.name}, ${d.address})`)}&travelmode=driving`
const timeAgo = (date) => {
  if (!date) return 'No confirmed update yet'
  const mins = Math.max(0, Math.floor((Date.now() - new Date(date).getTime()) / 60000))
  return mins < 1 ? 'Updated just now' : mins < 60 ? `Updated ${mins} minute${mins === 1 ? '' : 's'} ago` : `Updated ${Math.floor(mins / 60)} hour${Math.floor(mins / 60) === 1 ? '' : 's'} ago`
}
function Status({ item }) {
  const a = item.availability
  if (!a) return <span className="pz-status muted">Awaiting first update</span>
  const level = a.available === 0 ? 'full' : a.available / Math.max(a.total, 1) <= .2 ? 'limited' : 'open'
  return <span className={`pz-status ${level}`}>{level === 'full' ? '● Parking full' : level === 'limited' ? '● Limited parking' : '● Parking available'}</span>
}
function Header({ user, go, logout, showProfile, setAuthMode }) {
  return <header className="pz-nav"><button className="pz-brand" onClick={() => go(user ? user.role : 'landing')}><span className="pz-logo">P</span><span>parkzen</span></button><nav>{user && <><button onClick={() => go(user.role)}>{user.role === 'admin' ? 'Overview' : 'Dashboard'}</button>{user.role === 'customer' ? <button onClick={() => go('history')}>My activity</button> : user.role === 'manager' ? <button onClick={() => go('manager-history')}>Update history</button> : <button onClick={() => go('admin-users')}>Accounts</button>}<button onClick={showProfile}>Profile</button></>}</nav><div className="pz-nav-right">{user ? <><span className="pz-user-name">{user.name}</span><button className="pz-button secondary small" onClick={logout}>Sign out</button></> : <button className="pz-button secondary small" onClick={() => { setAuthMode('customer'); go('login') }}>Log in</button>}</div></header>
}

function App() {
  const [user, setUser] = useState(null), [page, setPage] = useState('landing')
  const [authMode, setAuthMode] = useState('customer'), [form, setForm] = useState({}), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  const [destinations, setDestinations] = useState([]), [query, setQuery] = useState(''), [kind, setKind] = useState('all'), [selected, setSelected] = useState(null), [history, setHistory] = useState([]), [predictionHistory, setPredictionHistory] = useState([]), [profile, setProfile] = useState(null)
  const [adminData, setAdminData] = useState(null), [adminUsers, setAdminUsers] = useState([])
  const [file, setFile] = useState(null), [managerDest, setManagerDest] = useState(''), [prediction, setPrediction] = useState(null), [saved, setSaved] = useState(false)
  const notice = (fn) => async (...args) => { setError(''); setBusy(true); try { await fn(...args) } catch (e) { setError(e.message) } finally { setBusy(false) } }
  const loadDestinations = useCallback(async () => { const d = await api(`/api/destinations?q=${encodeURIComponent(query)}&type=${kind}`); setDestinations(d.destinations); if (!managerDest && d.destinations.length) setManagerDest(d.destinations[0].id) }, [query, kind, managerDest])

  useEffect(() => { loadDestinations().catch(() => {}) }, [loadDestinations])
  useEffect(() => {
    if (!readToken()) return
    api('/api/auth/me').then(({ user: u }) => { setUser(u); setPage(u.role === 'manager' ? 'manager' : u.role === 'admin' ? 'admin' : 'customer') }).catch(() => localStorage.removeItem('parkzen-token'))
  }, [])
  useEffect(() => { if (user?.role === 'customer' && page === 'customer') api('/api/history').then(d => setHistory(d.history)).catch(() => {}) }, [user, page])
  useEffect(() => { if (user?.role === 'manager' && page === 'manager-history') api('/api/manager/predictions').then(d => setPredictionHistory(d.history)).catch(e => setError(e.message)) }, [user, page])
  useEffect(() => { if (user?.role === 'admin' && page === 'admin') api('/api/admin/overview').then(setAdminData).catch(e => setError(e.message)); if (user?.role === 'admin' && page === 'admin-users') api('/api/admin/users').then(d => setAdminUsers(d.users)).catch(e => setError(e.message)) }, [user, page])

  const doAuth = notice(async (event) => {
    event?.preventDefault()
    const mode = page === 'register' ? 'register' : 'login'
    if (mode === 'register' && form.password !== form.confirm) throw new Error('Passwords do not match.')
    const data = await api(`/api/auth/${mode}`, { method: 'POST', body: JSON.stringify(mode === 'register' ? { name: form.name, email: form.email, mobile: form.mobile, password: form.password } : { email: form.email, password: form.password, ...(authMode !== 'customer' ? { role: authMode } : {}) }) })
    if (mode === 'register') { setPage('login'); setError('Account created. Sign in with your new account.'); return }
    localStorage.setItem('parkzen-token', data.token); setUser(data.user); setPage(data.user.role === 'manager' ? 'manager' : data.user.role === 'admin' ? 'admin' : 'customer'); setForm({})
  })
  const logout = notice(async () => { await api('/api/auth/logout', { method: 'POST' }); localStorage.removeItem('parkzen-token'); setUser(null); setSelected(null); setAuthMode('customer'); setPage('landing') })
  const openDestination = notice(async (d) => { const result = await api(`/api/destinations/${d.id}`); setSelected(result.destination); setPage('detail') })
  const showProfile = notice(async () => { const result = await api('/api/profile'); setProfile(result.user); setPage('profile') })
  const analyze = notice(async (event) => { event.preventDefault(); if (!file) throw new Error('Choose a parking image first.'); const data = new FormData(); data.append('image', file); data.append('destination_id', managerDest); setPrediction(await api('/api/manager/analyze', { method: 'POST', body: data })); setSaved(false) })
  const confirm = notice(async () => { await api(`/api/manager/confirm/${prediction.prediction_id}`, { method: 'POST' }); setSaved(true); setPrediction(null); setFile(null); loadDestinations() })
  const saveProfile = notice(async (event) => { event.preventDefault(); const data = await api('/api/profile', { method: 'PATCH', body: JSON.stringify(profile) }); setProfile(data.user); setUser(data.user); setError('Profile saved.') })

  const go = (next) => { setError(''); setPage(next) }
  const auth = page === 'login' || page === 'register'
  return <div className="pz-app"><Header user={user} go={go} logout={logout} showProfile={showProfile} setAuthMode={setAuthMode} />{error && <div className={`pz-flash ${error.includes('created') || error.includes('saved') || error.includes('updated') ? 'success' : ''}`} role="status">{error}<button onClick={() => setError('')} aria-label="Dismiss">×</button></div>}
    {page === 'landing' && <main className="pz-landing"><div className="pz-hero-copy"><span className="pz-kicker">SMART PARKING. SMARTER DECISIONS.</span><h1>Get there with<br /><em>room to park.</em></h1><p>Know what parking looks like before you arrive. Find current car parking availability at your destination.</p><div className="pz-actions"><button className="pz-button" onClick={() => user ? go('customer') : (setAuthMode('customer'), go('login'))}>Find parking <span>↗</span></button></div><div className="pz-trust"><span>⌁</span> Live updates from on-site parking managers</div></div><div className="pz-role-actions"><button onClick={() => { setAuthMode('manager'); go('login') }}>Parking manager sign in ?</button><button onClick={() => { setAuthMode('admin'); go('login') }}>Administrator sign in ?</button></div><div className="pz-hero-art"><div className="pz-art-top"><span>YOUR ARRIVAL, MADE EASIER</span><span className="pz-live"><i /> PARKZEN LIVE</span></div><div className="pz-road"><div className="pz-road-line"/><div className="pz-car car-one">▰</div><div className="pz-car car-two">▰</div><div className="pz-pin">P</div><div className="pz-map-label">DESTINATION<br/><b>Closer, calmer arrivals.</b></div><div className="pz-availability"><span>NEAR YOUR DESTINATION</span><strong>Parking made<br/>predictable.</strong><span className="pz-mini-open"><i/> Check availability</span></div></div><div className="pz-art-bottom"><span>01 — SEARCH</span><span>02 — CHECK</span><span>03 — GO</span></div></div><section className="pz-how"><span className="pz-kicker">A BETTER WAY TO ARRIVE</span><div className="pz-how-grid"><article><small>01</small><h3>Choose where you’re going</h3><p>Search malls and restaurants in one simple place.</p></article><article><small>02</small><h3>See confirmed availability</h3><p>Managers update counts using ParkZen’s parking detection model.</p></article><article><small>03</small><h3>Navigate with confidence</h3><p>Open your chosen destination in Google Maps and get on your way.</p></article></div></section><footer className="pz-footer"><b>PARKZEN</b><span>Smart Parking. Smarter Decisions.</span></footer></main>}
    {auth && <main className="pz-auth"><div className="pz-auth-aside"><span className="pz-kicker">PARKZEN / {authMode.toUpperCase()}</span><h1>{page === 'register' ? 'A smoother arrival starts here.' : authMode === 'manager' ? 'Keep every space in view.' : 'Welcome back.'}</h1><p>{authMode === 'manager' ? 'Sign in to update parking availability for your location.' : 'Find current car parking availability before you head out.'}</p><div className="pz-auth-decoration"><div>⌖</div><span>Smart Parking<br/><b>Smarter Decisions.</b></span></div></div><form className="pz-auth-form" onSubmit={doAuth}><button type="button" className="pz-back" onClick={() => go('landing')}>← Back</button><span className="pz-kicker">{page === 'register' ? 'CREATE YOUR ACCOUNT' : 'SIGN IN TO PARKZEN'}</span><h2>{page === 'register' ? 'Create an account' : 'Sign in'}</h2><p>{page === 'register' ? 'Just the details we need to get you started.' : 'Enter your details to continue.'}</p>{page === 'register' && <><label>Full name<input required autoComplete="name" value={form.name || ''} onChange={e => setForm({...form,name:e.target.value})} placeholder="Your name"/></label><label>Mobile number<input required type="tel" autoComplete="tel" value={form.mobile || ''} onChange={e => setForm({...form,mobile:e.target.value})} placeholder="+91 98765 43210"/></label></>}<label>Email address<input required type="email" autoComplete="email" value={form.email || ''} onChange={e => setForm({...form,email:e.target.value})} placeholder="you@example.com"/></label><label>Password<input required type="password" autoComplete={page === 'register' ? 'new-password':'current-password'} value={form.password || ''} onChange={e => setForm({...form,password:e.target.value})} placeholder={page === 'register' ? 'At least 8 characters':'Your password'}/></label>{page === 'register' && <label>Confirm password<input required type="password" autoComplete="new-password" value={form.confirm || ''} onChange={e => setForm({...form,confirm:e.target.value})} placeholder="Enter password again"/></label>}<button disabled={busy} className="pz-button pz-submit">{busy ? 'Please wait…' : page === 'register' ? 'Create account →':'Sign in →'}</button><div className="pz-auth-switch">{page === 'register' ? <>Already have an account? <button type="button" onClick={() => go('login')}>Sign in</button></> : <>New to ParkZen? <button type="button" onClick={() => go('register')}>Create account</button></>}</div>{page === 'login' && authMode === 'customer' && <button type="button" className="pz-manager-link" onClick={() => setAuthMode('manager')}>Parking manager sign in →</button>}{page === 'login' && authMode === 'manager' && <button type="button" className="pz-manager-link" onClick={() => setAuthMode('customer')}>← Customer sign in</button>}</form></main>}
    {page === 'customer' && user?.role === 'customer' && <main className="pz-content"><div className="pz-page-heading"><span className="pz-kicker">YOUR NEXT STOP</span><h1>Where are you going?</h1><p>Find the latest confirmed car parking availability at your destination.</p></div><div className="pz-search"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search malls or restaurants"/><button onClick={() => setQuery('')}>Clear</button></div><div className="pz-filters">{[['all','All places'],['mall','Malls'],['restaurant','Restaurants']].map(([value,label])=><button key={value} className={kind===value?'active':''} onClick={()=>setKind(value)}>{label}</button>)}</div><div className="pz-dest-grid">{destinations.map(d=><article className="pz-dest-card" key={d.id}><div className={`pz-dest-image ${d.type}`}><span>{d.type==='mall'?'SHOPPING':'DINING'}</span><strong>{d.name.split(' ').map(x=>x[0]).join('')}</strong></div><div className="pz-dest-body"><div className="pz-dest-meta"><span>{d.type}</span><Status item={d}/></div><h2>{d.name}</h2><p>{d.address}</p>{d.availability ? <div className="pz-count-line"><b>{d.availability.available} <small>available</small></b><span>{d.availability.occupied} occupied · {d.availability.total} total</span></div> : <div className="pz-empty-update">Availability will appear after the manager confirms a new parking analysis.</div>}<div className="pz-card-bottom"><span>{timeAgo(d.availability?.updated_at)}</span><button onClick={()=>openDestination(d)}>View parking <span>→</span></button></div></div></article>)}</div>{destinations.length===0&&<div className="pz-empty-state">No destinations match “{query}”. Try another search.</div>}<section className="pz-history-preview"><div><span className="pz-kicker">RECENT ACTIVITY</span><h2>Your recent destinations</h2></div><button className="pz-link" onClick={()=>go('history')}>View history →</button>{history.slice(0,3).map((item,i)=><div className="pz-history-row" key={`${item.destination_id}-${i}`}><span className="pz-history-icon">⌖</span><b>{item.name}</b><small>{item.address}</small><time>{timeAgo(item.created_at)}</time></div>)}{!history.length&&<p>Destinations you view will appear here.</p>}</section></main>}
    {page === 'detail' && selected && <main className="pz-content"><button className="pz-back inline" onClick={()=>go('customer')}>← Back to destinations</button><div className="pz-detail-head"><div><span className="pz-kicker">{selected.type.toUpperCase()} / PARKING</span><h1>{selected.name}</h1><p>{selected.address}</p></div><a className="pz-button" href={mapsUrl(selected)} target="_blank" rel="noreferrer">Open in Google Maps ↗</a></div><div className="pz-detail-layout"><section className="pz-parking-card"><div className="pz-parking-top"><span>CAR PARKING AVAILABILITY</span><span className="pz-live"><i/> CONFIRMED DATA</span></div><Status item={selected}/>{selected.availability ? <><div className="pz-big-number"><strong>{selected.availability.available}</strong><span>available spaces</span></div><div className="pz-meter"><i style={{width:`${Math.min(100,selected.availability.available/Math.max(1,selected.availability.total)*100)}%`}}/></div><div className="pz-meter-label"><span>Availability</span><b>{Math.round(selected.availability.available/Math.max(1,selected.availability.total)*100)}%</b></div><div className="pz-detail-stats"><div><span>TOTAL CAR SLOTS</span><b>{selected.availability.total}</b></div><div><span>AVAILABLE</span><b className="green">{selected.availability.available}</b></div><div><span>OCCUPIED</span><b>{selected.availability.occupied}</b></div></div><p className="pz-updated">◷ {timeAgo(selected.availability.updated_at)}</p></> : <div className="pz-no-data"><span>⌁</span><h2>No confirmed update yet</h2><p>The parking manager hasn’t published a parking count for this destination. Please check again later.</p></div>}</section><aside className="pz-destination-aside"><span className="pz-kicker">YOUR DESTINATION</span><div className={`pz-aside-art ${selected.type}`}><span>⌖</span></div><h3>{selected.name}</h3><p>{selected.address}</p><div className="pz-coordinates">{selected.latitude.toFixed(4)}° N <span>·</span> {selected.longitude.toFixed(4)}° E</div><a className="pz-map-link" href={mapsUrl(selected)} target="_blank" rel="noreferrer">Directions to destination ↗</a></aside></div></main>}
    {page === 'manager' && user?.role === 'manager' && <main className="pz-content"><div className="pz-page-heading manager-heading"><span className="pz-kicker">PARKING OPERATIONS</span><h1>Good day, {user.name.split(' ')[0]}.</h1><p>Analyze a current car park image and review the result before publishing availability.</p><span className="pz-model-ready"><i/> YOLO MODEL READY</span></div><div className="pz-manager-grid"><form onSubmit={analyze} className="pz-upload-card"><div className="pz-step"><span>01</span><div><h2>Choose location</h2><p>Where was this image taken?</p></div></div><select value={managerDest} onChange={e=>setManagerDest(e.target.value)}>{destinations.map(d=><option key={d.id} value={d.id}>{d.name} · {d.address}</option>)}</select><div className="pz-step"><span>02</span><div><h2>Upload current image</h2><p>Use a clear JPG, PNG, or WebP, up to 12 MB.</p></div></div><label className="pz-dropzone"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)}/><span className="pz-upload-icon">↑</span><b>{file ? file.name : 'Choose an image or drop it here'}</b><small>{file ? `${(file.size/1024/1024).toFixed(1)} MB`:'No customer uploads. Manager images only.'}</small></label>{file && <img className="pz-image-preview" src={URL.createObjectURL(file)} alt="Selected parking area preview"/>}<button disabled={busy||!file} className="pz-button pz-submit">{busy?'Analyzing image…':'Analyze parking image →'}</button>{saved&&<div className="pz-inline-success">Availability successfully published for customers.</div>}</form><section className="pz-review-card"><div className="pz-step"><span>03</span><div><h2>Review & publish</h2><p>Confirm the AI detected car parking slots.</p></div></div>{prediction ? <><div className="pz-review-destination"><span>ANALYSIS FOR</span><b>{prediction.destination_name}</b></div><div className="pz-review-stats"><div><span>TOTAL SLOTS</span><b>{prediction.total}</b></div><div><span>AVAILABLE</span><b className="green">{prediction.available}</b></div><div><span>OCCUPIED</span><b>{prediction.occupied}</b></div></div><div className="pz-review-note">Review these results carefully. Customers will see this count after you confirm.</div><button disabled={busy} className="pz-button pz-submit" onClick={confirm}>Confirm & update availability →</button><button className="pz-cancel" onClick={()=>setPrediction(null)}>Discard analysis</button></>:<div className="pz-review-empty"><span>⌁</span><h3>Results will appear here</h3><p>Run an image analysis to review detected available and occupied car spaces.</p></div>}</section></div><section className="pz-manager-info"><span className="pz-kicker">HOW THIS UPDATE WORKS</span><div><b>Image → Detection → Confirmation → Live availability</b><p>ParkZen runs the existing YOLO car parking model on your uploaded image. Availability changes only after you confirm the results.</p></div></section></main>}
    {page === 'history' && user?.role === 'customer' && <main className="pz-content"><div className="pz-page-heading"><span className="pz-kicker">YOUR PARKZEN ACCOUNT</span><h1>Search activity</h1><p>Destinations where you’ve checked parking.</p></div><section className="pz-history-page">{history.length ? history.map((item,i)=><div className="pz-history-row" key={`${item.destination_id}-${i}`}><span className="pz-history-icon">⌖</span><b>{item.name}</b><small>{item.address}</small><time>{timeAgo(item.created_at)}</time><button onClick={()=>openDestination({id:item.destination_id})}>Check again →</button></div>):<div className="pz-empty-state">Your viewed destinations will show up here.</div>}</section></main>}
    {page === 'manager-history' && user?.role === 'manager' && <main className="pz-content"><div className="pz-page-heading"><span className="pz-kicker">PARKING OPERATIONS</span><h1>Update history</h1><p>Confirmed availability updates published by the manager team.</p></div><section className="pz-history-page">{predictionHistory.length ? predictionHistory.map(item=><div className="pz-history-row" key={item.id}><span className="pz-history-icon">✓</span><b>{item.destination_name}</b><small>{item.available} available · {item.occupied} occupied · {item.total} total</small><time>{timeAgo(item.confirmed_at)}</time></div>):<div className="pz-empty-state">No confirmed parking updates yet.</div>}</section></main>}
    {page === 'admin' && user?.role === 'admin' && <main className="pz-content"><div className="pz-page-heading"><span className="pz-kicker">PARKZEN / ADMINISTRATION</span><h1>Platform overview</h1><p>Monitor customer accounts, parking managers, destinations and published parking updates.</p></div><div className="pz-admin-stats">{[['CUSTOMERS',adminData?.customers],['MANAGERS',adminData?.managers],['DESTINATIONS',adminData?.destinations],['CONFIRMED UPDATES',adminData?.confirmed_updates]].map(([label,value])=><article key={label}><span>{label}</span><b>{value ?? '—'}</b></article>)}</div><section className="pz-history-page pz-admin-table"><div className="pz-table-heading"><h2>Latest confirmed availability</h2><button className="pz-link" onClick={()=>go('admin-users')}>Manage account directory →</button></div>{adminData?.latest_updates?.length ? adminData.latest_updates.map(item=><div className="pz-history-row" key={item.name}><span className="pz-history-icon">P</span><b>{item.name}</b><small>{item.available} available · {item.occupied} occupied · {item.total} total</small><time>{timeAgo(item.updated_at)}</time></div>):<div className="pz-empty-state">No confirmed parking updates have been published yet.</div>}</section></main>}
    {page === 'admin-users' && user?.role === 'admin' && <main className="pz-content"><div className="pz-page-heading"><span className="pz-kicker">PARKZEN / ADMINISTRATION</span><h1>Account directory</h1><p>Read-only overview of registered customers, managers, and administrators.</p></div><section className="pz-history-page pz-admin-table">{adminUsers.map(account=><div className="pz-history-row" key={account.id}><span className="pz-history-icon">{account.role[0].toUpperCase()}</span><b>{account.name}</b><small>{account.email} · {account.role}</small><time>{new Date(account.created_at).toLocaleDateString()}</time></div>)}{!adminUsers.length&&<div className="pz-empty-state">Loading account directory…</div>}</section></main>}
    {page === 'profile' && user && <main className="pz-content"><div className="pz-page-heading"><span className="pz-kicker">YOUR ACCOUNT</span><h1>Profile settings</h1><p>Keep your contact details up to date.</p></div><form className="pz-profile-form" onSubmit={saveProfile}><label>Full name<input value={profile?.name||''} onChange={e=>setProfile({...profile,name:e.target.value})} required/></label><label>Email address<input value={profile?.email||''} disabled/></label><label>Mobile number<input value={profile?.mobile||''} onChange={e=>setProfile({...profile,mobile:e.target.value})} required type="tel"/></label><button className="pz-button" disabled={busy}>Save changes</button></form></main>}
  </div>
}
export default App
